const menuItems = [
  {
    id: 1,
    amount: 0,
    title: "ไก่ทอดหาดใหญ่",
    price: 90,
    catagory: "burger",
    image: "image/kaitod.jpg",
    imagefordetail: "/image/kaitod.jpg",
    option: "image/icon-chicken.png",
    description_title: "รายละเอียด",
    description:
      "ไก่ทอดสูตรหาดใหญ่ รสเข้ม ไม่เหมือนใคร กรอบนอกนุ่มใน หอมกรุ่นพร้อมโรยหอมทอด ",
  },
  {
    id: 2,
    amount: 0,
    title: "ข้าวราดผัดกะเพราไก่ + ไข่ดาว",
    price: 60,
    catagory: "combo",
    image: "image/kapaokai.jpg",
    imagefordetail: "/image/kapaokai.jpg",
    option: "image/icon-chicken.png",
    description: "กระเพราไก่เสริฟพร้อมไข่ดาวขอบกรอบร้อนๆ",
  },
  {
    id: 3,
    amount: 0,
    title: "ข้าวราดผัดกะเพราหมูสับ + ไข่ดาว",
    price: 60,
    catagory: "combo",
    image: "image/kapaomoo.jpg",
    imagefordetail: "/image/kapaomoo.jpg",
    option: "image/icon-pork.png",
    description: "กระเพราหมูสับเสริฟพร้อมไข่ดาวขอบกรอบร้อนๆ",
  },
  {
    id: 4,
    amount: 0,
    title: "ข้าวราดผัดกะเพราหมูกรอบ + ไข่ดาว",
    price: 70,
    catagory: "combo",
    image: "image/kapaomookrob.jpg",
    imagefordetail: "/image/kapaomookrob.jpg",
    option: "image/icon-pork.png",
    description: "กระเพราหมูกรอบเสริฟพร้อมไข่ดาวขอบกรอบร้อนๆ",
  },
  {
    id: 5,
    amount: 0,
    title: "ชุดน้ำพริกกะปิปลาทูทอด",
    price: 100,
    catagory: "combo",
    image: "image/numprikkapi.jpg",
    imagefordetail: "/image/numprikkapi.jpg",
    option: "image/icon-fish.png",
    description: "น้ำพริกกะปิสูตรคุณยายเสริฟพร้อมผักต้มและปลาทูทอด",
  },
  {
    id: 6,
    amount: 0,
    title: "ผัดไทกุ้ง",
    price: 70,
    catagory: "snack",
    image: "image/padtai.jpg",
    imagefordetail: "/image/padtai.jpg",
    option: "image/icon-shrimp.png",
    description: "ผัดไทกุ้งสดๆจากทะเล",
  },
];
export default menuItems;
